package properties

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Attachment) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "AttachmentMacContentType":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentMacContentType")
					return
				}
				z.AttachmentMacContentType = nil
			} else {
				if z.AttachmentMacContentType == nil {
					z.AttachmentMacContentType = new(string)
				}
				*z.AttachmentMacContentType, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentMacContentType")
					return
				}
			}
		case "AttachmentOriginalPermissionType":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentOriginalPermissionType")
					return
				}
				z.AttachmentOriginalPermissionType = nil
			} else {
				if z.AttachmentOriginalPermissionType == nil {
					z.AttachmentOriginalPermissionType = new(int32)
				}
				*z.AttachmentOriginalPermissionType, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentOriginalPermissionType")
					return
				}
			}
		case "AttachmentPermissionType":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentPermissionType")
					return
				}
				z.AttachmentPermissionType = nil
			} else {
				if z.AttachmentPermissionType == nil {
					z.AttachmentPermissionType = new(int32)
				}
				*z.AttachmentPermissionType, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentPermissionType")
					return
				}
			}
		case "AttachmentProviderType":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentProviderType")
					return
				}
				z.AttachmentProviderType = nil
			} else {
				if z.AttachmentProviderType == nil {
					z.AttachmentProviderType = new(string)
				}
				*z.AttachmentProviderType, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentProviderType")
					return
				}
			}
		case "1409731":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachContentBase")
					return
				}
				z.AttachContentBase = nil
			} else {
				if z.AttachContentBase == nil {
					z.AttachContentBase = new(string)
				}
				*z.AttachContentBase, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachContentBase")
					return
				}
			}
		case "1409831":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachContentId")
					return
				}
				z.AttachContentId = nil
			} else {
				if z.AttachContentId == nil {
					z.AttachContentId = new(string)
				}
				*z.AttachContentId, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachContentId")
					return
				}
			}
		case "1409931":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachContentLocation")
					return
				}
				z.AttachContentLocation = nil
			} else {
				if z.AttachContentLocation == nil {
					z.AttachContentLocation = new(string)
				}
				*z.AttachContentLocation, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachContentLocation")
					return
				}
			}
		case "1408331":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachExtension")
					return
				}
				z.AttachExtension = nil
			} else {
				if z.AttachExtension == nil {
					z.AttachExtension = new(string)
				}
				*z.AttachExtension, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachExtension")
					return
				}
			}
		case "1408431":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachFilename")
					return
				}
				z.AttachFilename = nil
			} else {
				if z.AttachFilename == nil {
					z.AttachFilename = new(string)
				}
				*z.AttachFilename, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachFilename")
					return
				}
			}
		case "141003":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachFlags")
					return
				}
				z.AttachFlags = nil
			} else {
				if z.AttachFlags == nil {
					z.AttachFlags = new(int32)
				}
				*z.AttachFlags, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachFlags")
					return
				}
			}
		case "1408731":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachLongFilename")
					return
				}
				z.AttachLongFilename = nil
			} else {
				if z.AttachLongFilename == nil {
					z.AttachLongFilename = new(string)
				}
				*z.AttachLongFilename, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachLongFilename")
					return
				}
			}
		case "1409331":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachLongPathname")
					return
				}
				z.AttachLongPathname = nil
			} else {
				if z.AttachLongPathname == nil {
					z.AttachLongPathname = new(string)
				}
				*z.AttachLongPathname, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachLongPathname")
					return
				}
			}
		case "3276711":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentContactPhoto")
					return
				}
				z.AttachmentContactPhoto = nil
			} else {
				if z.AttachmentContactPhoto == nil {
					z.AttachmentContactPhoto = new(bool)
				}
				*z.AttachmentContactPhoto, err = dc.ReadBool()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentContactPhoto")
					return
				}
			}
		case "327653":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentFlags")
					return
				}
				z.AttachmentFlags = nil
			} else {
				if z.AttachmentFlags == nil {
					z.AttachmentFlags = new(int32)
				}
				*z.AttachmentFlags, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentFlags")
					return
				}
			}
		case "3276611":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentHidden")
					return
				}
				z.AttachmentHidden = nil
			} else {
				if z.AttachmentHidden == nil {
					z.AttachmentHidden = new(bool)
				}
				*z.AttachmentHidden, err = dc.ReadBool()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentHidden")
					return
				}
			}
		case "327623":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentLinkId")
					return
				}
				z.AttachmentLinkId = nil
			} else {
				if z.AttachmentLinkId == nil {
					z.AttachmentLinkId = new(int32)
				}
				*z.AttachmentLinkId, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachmentLinkId")
					return
				}
			}
		case "140853":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachMethod")
					return
				}
				z.AttachMethod = nil
			} else {
				if z.AttachMethod == nil {
					z.AttachMethod = new(int32)
				}
				*z.AttachMethod, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachMethod")
					return
				}
			}
		case "1409431":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachMimeTag")
					return
				}
				z.AttachMimeTag = nil
			} else {
				if z.AttachMimeTag == nil {
					z.AttachMimeTag = new(string)
				}
				*z.AttachMimeTag, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachMimeTag")
					return
				}
			}
		case "36173":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachNumber")
					return
				}
				z.AttachNumber = nil
			} else {
				if z.AttachNumber == nil {
					z.AttachNumber = new(int32)
				}
				*z.AttachNumber, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachNumber")
					return
				}
			}
		case "1408831":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachPathname")
					return
				}
				z.AttachPathname = nil
			} else {
				if z.AttachPathname == nil {
					z.AttachPathname = new(string)
				}
				*z.AttachPathname, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachPathname")
					return
				}
			}
		case "36163":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachSize")
					return
				}
				z.AttachSize = nil
			} else {
				if z.AttachSize == nil {
					z.AttachSize = new(int32)
				}
				*z.AttachSize, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "AttachSize")
					return
				}
			}
		case "1409231":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "AttachTransportName")
					return
				}
				z.AttachTransportName = nil
			} else {
				if z.AttachTransportName == nil {
					z.AttachTransportName = new(string)
				}
				*z.AttachTransportName, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "AttachTransportName")
					return
				}
			}
		case "1410731":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "TextAttachmentCharset")
					return
				}
				z.TextAttachmentCharset = nil
			} else {
				if z.TextAttachmentCharset == nil {
					z.TextAttachmentCharset = new(string)
				}
				*z.TextAttachmentCharset, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "TextAttachmentCharset")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Attachment) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 23
	// write "AttachmentMacContentType"
	err = en.Append(0xde, 0x0, 0x17, 0xb8, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	if z.AttachmentMacContentType == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachmentMacContentType)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentMacContentType")
			return
		}
	}
	// write "AttachmentOriginalPermissionType"
	err = en.Append(0xd9, 0x20, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	if z.AttachmentOriginalPermissionType == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachmentOriginalPermissionType)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentOriginalPermissionType")
			return
		}
	}
	// write "AttachmentPermissionType"
	err = en.Append(0xb8, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	if z.AttachmentPermissionType == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachmentPermissionType)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentPermissionType")
			return
		}
	}
	// write "AttachmentProviderType"
	err = en.Append(0xb6, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	if z.AttachmentProviderType == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachmentProviderType)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentProviderType")
			return
		}
	}
	// write "1409731"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x39, 0x37, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachContentBase == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachContentBase)
		if err != nil {
			err = msgp.WrapError(err, "AttachContentBase")
			return
		}
	}
	// write "1409831"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x39, 0x38, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachContentId == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachContentId)
		if err != nil {
			err = msgp.WrapError(err, "AttachContentId")
			return
		}
	}
	// write "1409931"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x39, 0x39, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachContentLocation == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachContentLocation)
		if err != nil {
			err = msgp.WrapError(err, "AttachContentLocation")
			return
		}
	}
	// write "1408331"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x38, 0x33, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachExtension == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachExtension)
		if err != nil {
			err = msgp.WrapError(err, "AttachExtension")
			return
		}
	}
	// write "1408431"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x38, 0x34, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachFilename == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachFilename)
		if err != nil {
			err = msgp.WrapError(err, "AttachFilename")
			return
		}
	}
	// write "141003"
	err = en.Append(0xa6, 0x31, 0x34, 0x31, 0x30, 0x30, 0x33)
	if err != nil {
		return
	}
	if z.AttachFlags == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachFlags)
		if err != nil {
			err = msgp.WrapError(err, "AttachFlags")
			return
		}
	}
	// write "1408731"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x38, 0x37, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachLongFilename == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachLongFilename)
		if err != nil {
			err = msgp.WrapError(err, "AttachLongFilename")
			return
		}
	}
	// write "1409331"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x39, 0x33, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachLongPathname == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachLongPathname)
		if err != nil {
			err = msgp.WrapError(err, "AttachLongPathname")
			return
		}
	}
	// write "3276711"
	err = en.Append(0xa7, 0x33, 0x32, 0x37, 0x36, 0x37, 0x31, 0x31)
	if err != nil {
		return
	}
	if z.AttachmentContactPhoto == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBool(*z.AttachmentContactPhoto)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentContactPhoto")
			return
		}
	}
	// write "327653"
	err = en.Append(0xa6, 0x33, 0x32, 0x37, 0x36, 0x35, 0x33)
	if err != nil {
		return
	}
	if z.AttachmentFlags == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachmentFlags)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentFlags")
			return
		}
	}
	// write "3276611"
	err = en.Append(0xa7, 0x33, 0x32, 0x37, 0x36, 0x36, 0x31, 0x31)
	if err != nil {
		return
	}
	if z.AttachmentHidden == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBool(*z.AttachmentHidden)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentHidden")
			return
		}
	}
	// write "327623"
	err = en.Append(0xa6, 0x33, 0x32, 0x37, 0x36, 0x32, 0x33)
	if err != nil {
		return
	}
	if z.AttachmentLinkId == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachmentLinkId)
		if err != nil {
			err = msgp.WrapError(err, "AttachmentLinkId")
			return
		}
	}
	// write "140853"
	err = en.Append(0xa6, 0x31, 0x34, 0x30, 0x38, 0x35, 0x33)
	if err != nil {
		return
	}
	if z.AttachMethod == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachMethod)
		if err != nil {
			err = msgp.WrapError(err, "AttachMethod")
			return
		}
	}
	// write "1409431"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x39, 0x34, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachMimeTag == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachMimeTag)
		if err != nil {
			err = msgp.WrapError(err, "AttachMimeTag")
			return
		}
	}
	// write "36173"
	err = en.Append(0xa5, 0x33, 0x36, 0x31, 0x37, 0x33)
	if err != nil {
		return
	}
	if z.AttachNumber == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachNumber)
		if err != nil {
			err = msgp.WrapError(err, "AttachNumber")
			return
		}
	}
	// write "1408831"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x38, 0x38, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachPathname == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachPathname)
		if err != nil {
			err = msgp.WrapError(err, "AttachPathname")
			return
		}
	}
	// write "36163"
	err = en.Append(0xa5, 0x33, 0x36, 0x31, 0x36, 0x33)
	if err != nil {
		return
	}
	if z.AttachSize == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteInt32(*z.AttachSize)
		if err != nil {
			err = msgp.WrapError(err, "AttachSize")
			return
		}
	}
	// write "1409231"
	err = en.Append(0xa7, 0x31, 0x34, 0x30, 0x39, 0x32, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.AttachTransportName == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.AttachTransportName)
		if err != nil {
			err = msgp.WrapError(err, "AttachTransportName")
			return
		}
	}
	// write "1410731"
	err = en.Append(0xa7, 0x31, 0x34, 0x31, 0x30, 0x37, 0x33, 0x31)
	if err != nil {
		return
	}
	if z.TextAttachmentCharset == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteString(*z.TextAttachmentCharset)
		if err != nil {
			err = msgp.WrapError(err, "TextAttachmentCharset")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Attachment) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 23
	// string "AttachmentMacContentType"
	o = append(o, 0xde, 0x0, 0x17, 0xb8, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65)
	if z.AttachmentMacContentType == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachmentMacContentType)
	}
	// string "AttachmentOriginalPermissionType"
	o = append(o, 0xd9, 0x20, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65)
	if z.AttachmentOriginalPermissionType == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachmentOriginalPermissionType)
	}
	// string "AttachmentPermissionType"
	o = append(o, 0xb8, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65)
	if z.AttachmentPermissionType == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachmentPermissionType)
	}
	// string "AttachmentProviderType"
	o = append(o, 0xb6, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65)
	if z.AttachmentProviderType == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachmentProviderType)
	}
	// string "1409731"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x39, 0x37, 0x33, 0x31)
	if z.AttachContentBase == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachContentBase)
	}
	// string "1409831"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x39, 0x38, 0x33, 0x31)
	if z.AttachContentId == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachContentId)
	}
	// string "1409931"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x39, 0x39, 0x33, 0x31)
	if z.AttachContentLocation == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachContentLocation)
	}
	// string "1408331"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x38, 0x33, 0x33, 0x31)
	if z.AttachExtension == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachExtension)
	}
	// string "1408431"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x38, 0x34, 0x33, 0x31)
	if z.AttachFilename == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachFilename)
	}
	// string "141003"
	o = append(o, 0xa6, 0x31, 0x34, 0x31, 0x30, 0x30, 0x33)
	if z.AttachFlags == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachFlags)
	}
	// string "1408731"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x38, 0x37, 0x33, 0x31)
	if z.AttachLongFilename == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachLongFilename)
	}
	// string "1409331"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x39, 0x33, 0x33, 0x31)
	if z.AttachLongPathname == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachLongPathname)
	}
	// string "3276711"
	o = append(o, 0xa7, 0x33, 0x32, 0x37, 0x36, 0x37, 0x31, 0x31)
	if z.AttachmentContactPhoto == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBool(o, *z.AttachmentContactPhoto)
	}
	// string "327653"
	o = append(o, 0xa6, 0x33, 0x32, 0x37, 0x36, 0x35, 0x33)
	if z.AttachmentFlags == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachmentFlags)
	}
	// string "3276611"
	o = append(o, 0xa7, 0x33, 0x32, 0x37, 0x36, 0x36, 0x31, 0x31)
	if z.AttachmentHidden == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBool(o, *z.AttachmentHidden)
	}
	// string "327623"
	o = append(o, 0xa6, 0x33, 0x32, 0x37, 0x36, 0x32, 0x33)
	if z.AttachmentLinkId == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachmentLinkId)
	}
	// string "140853"
	o = append(o, 0xa6, 0x31, 0x34, 0x30, 0x38, 0x35, 0x33)
	if z.AttachMethod == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachMethod)
	}
	// string "1409431"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x39, 0x34, 0x33, 0x31)
	if z.AttachMimeTag == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachMimeTag)
	}
	// string "36173"
	o = append(o, 0xa5, 0x33, 0x36, 0x31, 0x37, 0x33)
	if z.AttachNumber == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachNumber)
	}
	// string "1408831"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x38, 0x38, 0x33, 0x31)
	if z.AttachPathname == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachPathname)
	}
	// string "36163"
	o = append(o, 0xa5, 0x33, 0x36, 0x31, 0x36, 0x33)
	if z.AttachSize == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendInt32(o, *z.AttachSize)
	}
	// string "1409231"
	o = append(o, 0xa7, 0x31, 0x34, 0x30, 0x39, 0x32, 0x33, 0x31)
	if z.AttachTransportName == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.AttachTransportName)
	}
	// string "1410731"
	o = append(o, 0xa7, 0x31, 0x34, 0x31, 0x30, 0x37, 0x33, 0x31)
	if z.TextAttachmentCharset == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendString(o, *z.TextAttachmentCharset)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Attachment) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "AttachmentMacContentType":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentMacContentType = nil
			} else {
				if z.AttachmentMacContentType == nil {
					z.AttachmentMacContentType = new(string)
				}
				*z.AttachmentMacContentType, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentMacContentType")
					return
				}
			}
		case "AttachmentOriginalPermissionType":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentOriginalPermissionType = nil
			} else {
				if z.AttachmentOriginalPermissionType == nil {
					z.AttachmentOriginalPermissionType = new(int32)
				}
				*z.AttachmentOriginalPermissionType, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentOriginalPermissionType")
					return
				}
			}
		case "AttachmentPermissionType":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentPermissionType = nil
			} else {
				if z.AttachmentPermissionType == nil {
					z.AttachmentPermissionType = new(int32)
				}
				*z.AttachmentPermissionType, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentPermissionType")
					return
				}
			}
		case "AttachmentProviderType":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentProviderType = nil
			} else {
				if z.AttachmentProviderType == nil {
					z.AttachmentProviderType = new(string)
				}
				*z.AttachmentProviderType, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentProviderType")
					return
				}
			}
		case "1409731":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachContentBase = nil
			} else {
				if z.AttachContentBase == nil {
					z.AttachContentBase = new(string)
				}
				*z.AttachContentBase, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachContentBase")
					return
				}
			}
		case "1409831":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachContentId = nil
			} else {
				if z.AttachContentId == nil {
					z.AttachContentId = new(string)
				}
				*z.AttachContentId, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachContentId")
					return
				}
			}
		case "1409931":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachContentLocation = nil
			} else {
				if z.AttachContentLocation == nil {
					z.AttachContentLocation = new(string)
				}
				*z.AttachContentLocation, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachContentLocation")
					return
				}
			}
		case "1408331":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachExtension = nil
			} else {
				if z.AttachExtension == nil {
					z.AttachExtension = new(string)
				}
				*z.AttachExtension, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachExtension")
					return
				}
			}
		case "1408431":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachFilename = nil
			} else {
				if z.AttachFilename == nil {
					z.AttachFilename = new(string)
				}
				*z.AttachFilename, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachFilename")
					return
				}
			}
		case "141003":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachFlags = nil
			} else {
				if z.AttachFlags == nil {
					z.AttachFlags = new(int32)
				}
				*z.AttachFlags, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachFlags")
					return
				}
			}
		case "1408731":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachLongFilename = nil
			} else {
				if z.AttachLongFilename == nil {
					z.AttachLongFilename = new(string)
				}
				*z.AttachLongFilename, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachLongFilename")
					return
				}
			}
		case "1409331":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachLongPathname = nil
			} else {
				if z.AttachLongPathname == nil {
					z.AttachLongPathname = new(string)
				}
				*z.AttachLongPathname, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachLongPathname")
					return
				}
			}
		case "3276711":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentContactPhoto = nil
			} else {
				if z.AttachmentContactPhoto == nil {
					z.AttachmentContactPhoto = new(bool)
				}
				*z.AttachmentContactPhoto, bts, err = msgp.ReadBoolBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentContactPhoto")
					return
				}
			}
		case "327653":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentFlags = nil
			} else {
				if z.AttachmentFlags == nil {
					z.AttachmentFlags = new(int32)
				}
				*z.AttachmentFlags, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentFlags")
					return
				}
			}
		case "3276611":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentHidden = nil
			} else {
				if z.AttachmentHidden == nil {
					z.AttachmentHidden = new(bool)
				}
				*z.AttachmentHidden, bts, err = msgp.ReadBoolBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentHidden")
					return
				}
			}
		case "327623":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachmentLinkId = nil
			} else {
				if z.AttachmentLinkId == nil {
					z.AttachmentLinkId = new(int32)
				}
				*z.AttachmentLinkId, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachmentLinkId")
					return
				}
			}
		case "140853":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachMethod = nil
			} else {
				if z.AttachMethod == nil {
					z.AttachMethod = new(int32)
				}
				*z.AttachMethod, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachMethod")
					return
				}
			}
		case "1409431":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachMimeTag = nil
			} else {
				if z.AttachMimeTag == nil {
					z.AttachMimeTag = new(string)
				}
				*z.AttachMimeTag, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachMimeTag")
					return
				}
			}
		case "36173":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachNumber = nil
			} else {
				if z.AttachNumber == nil {
					z.AttachNumber = new(int32)
				}
				*z.AttachNumber, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachNumber")
					return
				}
			}
		case "1408831":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachPathname = nil
			} else {
				if z.AttachPathname == nil {
					z.AttachPathname = new(string)
				}
				*z.AttachPathname, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachPathname")
					return
				}
			}
		case "36163":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachSize = nil
			} else {
				if z.AttachSize == nil {
					z.AttachSize = new(int32)
				}
				*z.AttachSize, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachSize")
					return
				}
			}
		case "1409231":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.AttachTransportName = nil
			} else {
				if z.AttachTransportName == nil {
					z.AttachTransportName = new(string)
				}
				*z.AttachTransportName, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "AttachTransportName")
					return
				}
			}
		case "1410731":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.TextAttachmentCharset = nil
			} else {
				if z.TextAttachmentCharset == nil {
					z.TextAttachmentCharset = new(string)
				}
				*z.TextAttachmentCharset, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "TextAttachmentCharset")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Attachment) Msgsize() (s int) {
	s = 3 + 25
	if z.AttachmentMacContentType == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachmentMacContentType)
	}
	s += 34
	if z.AttachmentOriginalPermissionType == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 25
	if z.AttachmentPermissionType == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 23
	if z.AttachmentProviderType == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachmentProviderType)
	}
	s += 8
	if z.AttachContentBase == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachContentBase)
	}
	s += 8
	if z.AttachContentId == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachContentId)
	}
	s += 8
	if z.AttachContentLocation == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachContentLocation)
	}
	s += 8
	if z.AttachExtension == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachExtension)
	}
	s += 8
	if z.AttachFilename == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachFilename)
	}
	s += 7
	if z.AttachFlags == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 8
	if z.AttachLongFilename == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachLongFilename)
	}
	s += 8
	if z.AttachLongPathname == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachLongPathname)
	}
	s += 8
	if z.AttachmentContactPhoto == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BoolSize
	}
	s += 7
	if z.AttachmentFlags == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 8
	if z.AttachmentHidden == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BoolSize
	}
	s += 7
	if z.AttachmentLinkId == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 7
	if z.AttachMethod == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 8
	if z.AttachMimeTag == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachMimeTag)
	}
	s += 6
	if z.AttachNumber == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 8
	if z.AttachPathname == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachPathname)
	}
	s += 6
	if z.AttachSize == nil {
		s += msgp.NilSize
	} else {
		s += msgp.Int32Size
	}
	s += 8
	if z.AttachTransportName == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.AttachTransportName)
	}
	s += 8
	if z.TextAttachmentCharset == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.TextAttachmentCharset)
	}
	return
}
